CleerenCore/Controllers/PieController.cs
using CleerenCore.Models;
using CleerenCore.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CleerenCore.Controllers
{
    public class PieController : Controller
    {
        private ICategoryRepository _categoryRepository;
        private IPieRepository _pieRepository;
        

        public PieController(ICategoryRepository categoryRepository,IPieRepository pieRepository)
        {
            _categoryRepository = categoryRepository;
            _pieRepository = pieRepository;          

        }

        [HttpGet]
        public IActionResult Index()
        {          

            PieListVM pieListVM = new PieListVM()
            { 
                Pies=_pieRepository.GetAllPies().ToList(),
                CurrentCategory="Cheese Cakes"
            };

            return View(pieListVM);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var pie = _pieRepository.GetPieById(id.Value);

            return View(pie);
        }

    }
}

CleerenCore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pie" asp-action="Index">MvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pie" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ms-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout : @User.Identity.Name
                                    </button>
                                </form>
                               
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" width="200" height="200" />
                </p>
            </div>

            <div class="col-md-9">
                @RenderBody()
            </div>

        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>